frontend/website/routes/front.py
"""
    This file is part of Vistory.

    Vistory is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Vistory is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Vistory.  If not, see <http://www.gnu.org/licenses/>.
"""
import json
from os import path

import requests
from flask import render_template, Blueprint, current_app as cur_app, request
from marshmallow import fields
from webargs.flaskparser import use_args

from website import sender
from website.forms import NewPostForm, NewChannelForm
from website.jsons.errors import ErrorJson, UnprocessableEntityJson

bp = Blueprint('bp', __name__)
PAGES = [
    'search_results.vue',
    'profile.vue',
    'posts.vue',
    'people.vue',
    'channels.vue'
]
IMG_ALLOWED_EXTENSIONS = {'.png', '.jpg', '.jpeg'}
VIDEO_ALLOWED_EXTENSIONS = {'.mp4'}
bearer_args = {
    'Authorization': fields.Str(required=False)
}


def get_file_type(file):
    extension = path.splitext(file.filename)[1].lower()
    if extension in IMG_ALLOWED_EXTENSIONS:
        return 'image'
    if extension in VIDEO_ALLOWED_EXTENSIONS:
        return 'video'
    return False


@bp.route('/')
def home():
    sign_in_url = '{0}/oauth/authorize?client_id={1}&response_type=code&state={2}'\
        .format(cur_app.config['AUTH_SERVICE'], cur_app.config['CLIENT_ID'], cur_app.config['SECRET_KEY'])
    return render_template("home.html", sign_in_url=sign_in_url)


@bp.route('/pages/new_channel.vue', methods=['GET', 'POST'])
@use_args(bearer_args, locations=['headers'])
def new_channel(args):
    form = NewChannelForm(request.form)
    if request.method == 'POST' and form.validate():
        url = cur_app.config['AUTH_SERVICE'] + '/api/channels'
        data = json.dumps({'name': form.name.data, 'description': form.description.data})
        headers = {
            'Auhtorization':  args['Authorization'],
            'Content-Type': 'application/json'
        }
        return sender.post(url, headers=headers, body=data)

    return render_template('pages/new_channel.vue', form=form)


@bp.route('/pages/new_post.vue', methods=['GET', 'POST'])
def new_post():
    form = NewPostForm(request.form)
    form.file.data = request.files.get('file', '')
    if request.method == 'POST' and form.validate():
        file = form.file.data
        f_type = get_file_type(file)
        if not f_type:
            return UnprocessableEntityJson('Unsupported file type.').to_json(), 422
        files = {f_type: file.read()}
        fs_url = cur_app.config['FS_SERVICE'] + '/api/' + f_type + 's'
        response = requests.post(fs_url, files=files)

    return render_template('pages/new_post.vue', form=form)


@bp.route('/pages/<page_name>')
def get_page(page_name):
    if page_name not in PAGES:
        return ErrorJson(404, 'NOT_FOUND', 'Requested page not found.').to_json(), 404
    return render_template('pages/%s' % page_name)

frontend/website/templates/callback.html
<!DOCTYPE html>
<html lang="en" class="has-navbar-fixed-top">
    <head>
        <meta charset="UTF-8">
        <script type="application/javascript" src="{{ url_for('static', filename='js/oauth2.js') }}"></script>
        <title>Vistory</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
        <script type="application/javascript">
            document.addEventListener('DOMContentLoaded', function() {
                let token = {{ token|tojson }};
                if (token.hasOwnProperty('access_token')) {
                    localStorage.setItem('access_token', token['access_token']);
                }
                if (token.hasOwnProperty('refresh_token')) {
                    localStorage.setItem('refresh_token', token['refresh_token']);
                }
                window.location.href = '{{ url_for('bp.home') }}';
            });
        </script>
    </body>
</html>

frontend/website/templates/header.html
<nav class="navbar is-fixed-top has-shadow" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <a class="navbar-item is-size-3" href="#">
            <span class="has-text-primary">Vi</span>story
        </a>
        <div class="navbar-burger burger" data-target="mainMenu">
            <span></span>
            <span></span>
            <span></span>
        </div>
    </div>
    <div id="mainMenu" class="navbar-menu">
        <div class="navbar-end">
            <div class="navbar-item">{% include 'search.html' %}</div>
            <div v-if="signed" class="navbar-item has-dropdown is-hoverable">
                <a class="navbar-link">{( username )}</a>
                <div class="navbar-dropdown is-boxed">
                    <a class="navbar-item" v-on:click="signOut" href="#">Exit</a>
                </div>
            </div>
            <template v-else>
                <div class="navbar-item">
                    <a class="button is-primary" href="{{ sign_in_url }}">Sign in</a>
                </div>
            </template>
        </div>
    </div>
  </div>
</nav>

frontend/website/templates/home.html
<!DOCTYPE html>
<script type="text/x-template" id="right-menu-item">
    <li
            @click.stop="toggleRowActive"
            :key="index">
        <a v-bind:class="{'is-active': active}">
            <span class="icon">
                <i class="fas" v-bind:class="icon"></i>
            </span>
            {( title )}
        </a>
    </li>
</script>
<html lang="en" class="has-navbar-fixed-top">
    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/bulma.css') }}">
        <link href="{{ url_for('static', filename='fontawesome/css/all.css') }}" rel="stylesheet">
        <script type="application/javascript" src="{{ url_for('static', filename='js/vue.js') }}" defer></script>
        <script type="application/javascript" src="{{ url_for('static', filename='js/httpVueLoader.js') }}" defer></script>
        <script type="application/javascript" src="{{ url_for('static', filename='js/axios.js') }}" defer></script>
        <script type="application/javascript" src="{{ url_for('static', filename='js/oauth2.js') }}" defer></script>
        <script type="application/javascript" src="{{ url_for('static', filename='js/app.js') }}" defer></script>
        <title>Vistory</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
        <div id="page">
            <template>
                <header>
                    {% include 'header.html' %}
                </header>
                <section class="container">
                    <div class="columns vi-offset-top-xs">
                        <div class="column" style="overflow-y: auto;">
                            <h1 class="title">{( mainTitle )}</h1>
                            <component :is="content"></component>
                        </div>
                        <div id="rightBar" class="column is-3" v-if="signed">
                            <div class="box">
                                <aside class="menu">
                                    <p class="menu-label">General</p>
                                    <ul class="menu-list">
                                        <right-menu-item
                                                :title="section.title"
                                                :icon="section.icon"
                                                v-for="(section, index) in sections"
                                                :active="index === selectedIndex"
                                                :index="index"
                                                :key="section.id"
                                                :listener="onItemSelected"
                                                @newactive="selectedIndex = $event">
                                        </right-menu-item>
                                    </ul>
                                </aside>
                            </div>
                            <button type="button" class="button is-primary is-fullwidth" v-on:click="onNewPost">New post</button><br>
                            <button type="button" class="button is-primary is-fullwidth" v-on:click="onNewChannel">New channel</button>
                        </div>
                    </div>
                </section>
            </template>
        </div>
    </body>
</html>

frontend/website/templates/post.html
<div class="tile is-child box" style="height: 20rem;">

</div>

frontend/website/templates/search.html
<div class="field has-addons">
    <div class="control">
        <input class="input" type="text" placeholder="Search..." v-model="searchRequest">
    </div>
    <div class="control">
        <a class="button is-primary" v-on:click="onSearch">Find</a>
    </div>
</div>